# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PulserGUI.ui'
#
# Created: Fri May 25 11:39:57 2018
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 733)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblFreq = QtGui.QLabel(self.centralwidget)
        self.lblFreq.setObjectName("lblFreq")
        self.horizontalLayout_2.addWidget(self.lblFreq)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboPulseFreq = QtGui.QComboBox(self.centralwidget)
        self.comboPulseFreq.setObjectName("comboPulseFreq")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.comboPulseFreq.addItem("")
        self.horizontalLayout_2.addWidget(self.comboPulseFreq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblFreq_2 = QtGui.QLabel(self.centralwidget)
        self.lblFreq_2.setObjectName("lblFreq_2")
        self.horizontalLayout_3.addWidget(self.lblFreq_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lEditInitialWidth = QtGui.QLineEdit(self.centralwidget)
        self.lEditInitialWidth.setObjectName("lEditInitialWidth")
        self.horizontalLayout_3.addWidget(self.lEditInitialWidth)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lEditFinalWidth = QtGui.QLineEdit(self.centralwidget)
        self.lEditFinalWidth.setObjectName("lEditFinalWidth")
        self.horizontalLayout_4.addWidget(self.lEditFinalWidth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioBtnPulseOnOff = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnPulseOnOff.setChecked(False)
        self.radioBtnPulseOnOff.setAutoExclusive(False)
        self.radioBtnPulseOnOff.setObjectName("radioBtnPulseOnOff")
        self.horizontalLayout_5.addWidget(self.radioBtnPulseOnOff)
        self.radioBtnFineIncrementScan = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnFineIncrementScan.setObjectName("radioBtnFineIncrementScan")
        self.horizontalLayout_5.addWidget(self.radioBtnFineIncrementScan)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cBoxCH0 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH0.setObjectName("cBoxCH0")
        self.horizontalLayout_7.addWidget(self.cBoxCH0)
        self.cBoxCH1 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH1.setObjectName("cBoxCH1")
        self.horizontalLayout_7.addWidget(self.cBoxCH1)
        self.cBoxCH2 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH2.setObjectName("cBoxCH2")
        self.horizontalLayout_7.addWidget(self.cBoxCH2)
        self.cBoxCH3 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH3.setObjectName("cBoxCH3")
        self.horizontalLayout_7.addWidget(self.cBoxCH3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cBoxCH4 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH4.setObjectName("cBoxCH4")
        self.horizontalLayout_15.addWidget(self.cBoxCH4)
        self.cBoxCH5 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH5.setObjectName("cBoxCH5")
        self.horizontalLayout_15.addWidget(self.cBoxCH5)
        self.cBoxCH6 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH6.setObjectName("cBoxCH6")
        self.horizontalLayout_15.addWidget(self.cBoxCH6)
        self.cBoxCH7 = QtGui.QCheckBox(self.centralwidget)
        self.cBoxCH7.setObjectName("cBoxCH7")
        self.horizontalLayout_15.addWidget(self.cBoxCH7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.txtBoxSerialPortAddr = QtGui.QLineEdit(self.centralwidget)
        self.txtBoxSerialPortAddr.setEnabled(False)
        self.txtBoxSerialPortAddr.setObjectName("txtBoxSerialPortAddr")
        self.horizontalLayout_6.addWidget(self.txtBoxSerialPortAddr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblConnectionStatus = QtGui.QLabel(self.centralwidget)
        self.lblConnectionStatus.setObjectName("lblConnectionStatus")
        self.horizontalLayout_9.addWidget(self.lblConnectionStatus)
        self.btnConnect = QtGui.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_9.addWidget(self.btnConnect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnScanWidths = QtGui.QPushButton(self.centralwidget)
        self.btnScanWidths.setObjectName("btnScanWidths")
        self.horizontalLayout_14.addWidget(self.btnScanWidths)
        self.btnScanFreq = QtGui.QPushButton(self.centralwidget)
        self.btnScanFreq.setObjectName("btnScanFreq")
        self.horizontalLayout_14.addWidget(self.btnScanFreq)
        self.btnRunFullScan = QtGui.QPushButton(self.centralwidget)
        self.btnRunFullScan.setEnabled(True)
        self.btnRunFullScan.setObjectName("btnRunFullScan")
        self.horizontalLayout_14.addWidget(self.btnRunFullScan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnSetRegisters = QtGui.QPushButton(self.centralwidget)
        self.btnSetRegisters.setObjectName("btnSetRegisters")
        self.horizontalLayout_12.addWidget(self.btnSetRegisters)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.txtEditDebugMsg = QtGui.QTextEdit(self.centralwidget)
        self.txtEditDebugMsg.setMaximumSize(QtCore.QSize(16777215, 300))
        self.txtEditDebugMsg.setObjectName("txtEditDebugMsg")
        self.verticalLayout.addWidget(self.txtEditDebugMsg)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboPulseFreq, self.lEditInitialWidth)
        MainWindow.setTabOrder(self.lEditInitialWidth, self.lEditFinalWidth)
        MainWindow.setTabOrder(self.lEditFinalWidth, self.radioBtnPulseOnOff)
        MainWindow.setTabOrder(self.radioBtnPulseOnOff, self.radioBtnFineIncrementScan)
        MainWindow.setTabOrder(self.radioBtnFineIncrementScan, self.btnConnect)
        MainWindow.setTabOrder(self.btnConnect, self.txtBoxSerialPortAddr)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pulser", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreq.setText(QtGui.QApplication.translate("MainWindow", "Pulse Frequency (KHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(0, QtGui.QApplication.translate("MainWindow", "1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(1, QtGui.QApplication.translate("MainWindow", "2 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(2, QtGui.QApplication.translate("MainWindow", "3 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(3, QtGui.QApplication.translate("MainWindow", "4 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(4, QtGui.QApplication.translate("MainWindow", "5 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(5, QtGui.QApplication.translate("MainWindow", "6 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(6, QtGui.QApplication.translate("MainWindow", "7 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(7, QtGui.QApplication.translate("MainWindow", "8 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(8, QtGui.QApplication.translate("MainWindow", "9 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPulseFreq.setItemText(9, QtGui.QApplication.translate("MainWindow", "10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreq_2.setText(QtGui.QApplication.translate("MainWindow", "Initial Pulse Width (max 50)", None, QtGui.QApplication.UnicodeUTF8))
        self.lEditInitialWidth.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Final Pulse Width (max 50)", None, QtGui.QApplication.UnicodeUTF8))
        self.lEditFinalWidth.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnPulseOnOff.setText(QtGui.QApplication.translate("MainWindow", "Pulses On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnFineIncrementScan.setText(QtGui.QApplication.translate("MainWindow", "Fine Increment Scan On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH0.setText(QtGui.QApplication.translate("MainWindow", "CH0", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH1.setText(QtGui.QApplication.translate("MainWindow", "CH1", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH2.setText(QtGui.QApplication.translate("MainWindow", "CH2", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH3.setText(QtGui.QApplication.translate("MainWindow", "CH3", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH4.setText(QtGui.QApplication.translate("MainWindow", "CH4", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH5.setText(QtGui.QApplication.translate("MainWindow", "CH5", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH6.setText(QtGui.QApplication.translate("MainWindow", "CH6", None, QtGui.QApplication.UnicodeUTF8))
        self.cBoxCH7.setText(QtGui.QApplication.translate("MainWindow", "CH7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Serial Port ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConnectionStatus.setText(QtGui.QApplication.translate("MainWindow", "Not Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanWidths.setText(QtGui.QApplication.translate("MainWindow", "Scan Widths", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScanFreq.setText(QtGui.QApplication.translate("MainWindow", "Scan Freq", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRunFullScan.setText(QtGui.QApplication.translate("MainWindow", "Run Full Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetRegisters.setText(QtGui.QApplication.translate("MainWindow", "Set FPGA Registers", None, QtGui.QApplication.UnicodeUTF8))

